name: CI pipeline

on:
  push:
    branches: [ "main" ]   # jalan setiap ada push ke main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .   # publish semua file di repo (index.html, css, js, dll)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
